[build]
  command = "yarn build"
  functions = "vue-app/netlify/functions"
  publish = "vue-app/dist"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Accept, Authorization"